[package]
name = "rust_gameboy_emurator"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.228"

[dependencies.sdl2]
version = "0.38.0"
features = ["bundled", "raw-window-handle", "static-link"]
